### ISSUE TITLE
Crash on Invalid JSON

### ISSUE THREAD

**Issue by Jip-Hop** [misterhat/omdb#10]
Hi misterhat,

There are some known cases where OMDb returns invalid JSON. Because the omdb node module doesn't handle these errors, the program crashes. The problem is that Needle will not always return an object, only if it is able to parse the response. Else it will return a string. Object.keys won't work with a string.

/omdb/node_modules/omdb/index.js:167
            Object.keys(movie).forEach(function (key) {
                   ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at /omdb/node_modules/omdb/index.js:167:20
    at done (/omdb/node_modules/omdb/node_modules/needle/lib/needle.js:234:9)
    at PassThrough.<anonymous> (/omdb/node_modules/omdb/node_modules/needle/lib/needle.js:363:11)
    at PassThrough.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)

Cases of invalid JSON:
First case: An escaped single quote in the movie plot (e.g. tt0477543)
Second case: Unescaped backslash in the movie title (e.g. tt0102445: “Title”: “Miliardi\Millions”)
The thirds case: The plot contains an invalid character \u001F (e.g. tt2091423)

I think it would be nice if your module could account for these exceptions and not crash.

Two suggestions: check for known problems in the returned JSON and try to fix them (remove illegal characters and escape un-escaped stuff). The second suggestions would be to use try catch and return undefined or an error in case the parsing is unsuccessful.

Does that sound like a good idea? Do you have time to implement a solution?

**Comment by misterhat** [comment]
Let me know if this is fixed in https://github.com/misterhat/omdb/commit/f9389c36ee889eaf26dda5ae770177d69cc48223.

**Comment by Jip-Hop** [comment]
Hi misterhat,

Thanks for looking at it and implementing a fix! At first sight I couldn't believe it also fixed case 1 and 2 but it actually does :) The problem is fixed!

Maybe you could still have a look here: https://github.com/freethenation/durable-json-lint/issues/1. The author uses a slightly different regex to fix the problem: `json = json.replace(/[\u0000-\u001f]/g, function(c){ return JSON.stringify(c).slice(1,-1);} );` This will not remove the characters, but make them valid JSON. The durable-json-lint module is used to fix case 1 and 2. This module could also be used to fix other yet unknown issues with the JSON response from OMDb, hence making your module even more stable.

Why did you add `var i;` here https://github.com/misterhat/omdb/blob/f9389c36ee889eaf26dda5ae770177d69cc48223/index.js#L148? I think it could be removed.

**Comment by Jip-Hop** [comment]
I came across 3 more instances of invalid JSON, which can't be parsed even with your new fix. I'm glad the module doesn't crash but it still doesn't return any data.

In one of the 3 cases, the data could be automatically corrected by using durable-json-lint. Would you consider including durable-json-lint?

The problems ids are:

tt0120690: http://www.omdbapi.com/?i=tt0120690&plot=full&r=json
The plot has an unescaped backslash. This was automatically corrected by durable-json-lint.

tt0255309: http://www.omdbapi.com/?i=tt0255309&plot=full&r=json
Here the double quotes in the plot have been escaped twice, e.g.: \\"Prithvi \\". This occurs 4 times in the plot.

tt2828840: http://www.omdbapi.com/?i=tt2828840&plot=full&r=json
Here the double quote closing the plot has been escaped.

**Comment by misterhat** [comment]
I'll look into implementing that module.

**Comment by misterhat** [comment]
Sorry about the delay. I implemented durable-json-lint in https://github.com/misterhat/omdb/commit/e89f31ad8c05083e0903a96eb86473c2e27a57f0.

**Comment by Jip-Hop** [comment]
Awesome :)
