### ISSUE TITLE
Consuming lists with commas in items

### ISSUE THREAD

**Issue by mitom** [misterhat/omdb#15]
As a specific example:
````json
{  
  "Title":"Captain Phillips",
  "Year":"2013",
  "Rated":"PG-13",
  "Released":"11 Oct 2013",
  "Runtime":"134 min",
  "Genre":"Biography, Drama, Thriller",
  "Director":"Paul Greengrass",
  "Writer":"Billy Ray (screenplay), Richard Phillips (based upon the book \"A Captain's Duty: Somali Pirates,  Navy SEALS,  and Dangerous Days at Sea\" by), Stephan Talty (based upon the book \"A Captain's Duty: Somali Pirates,  Navy SEALS,  and Dangerous Days at Sea\" by)",
  "Actors":"Tom Hanks, Catherine Keener, Barkhad Abdi, Barkhad Abdirahman",
  "Plot":"The true story of Captain Richard Phillips and the 2009 hijacking by Somali pirates of the US-flagged MV Maersk Alabama, the first American cargo ship to be hijacked in two hundred years.",
  "Language":"English, Somali",
  "Country":"USA",
  "Awards":"Nominated for 6 Oscars. Another 16 wins & 128 nominations.",
  "Poster":"http://ia.media-imdb.com/images/M/MV5BMTQzNzExMDg3Ml5BMl5BanBnXkFtZTgwODU1NzEzMDE@._V1_SX300.jpg",
  "Metascore":"83",
  "imdbRating":"7.9",
  "imdbVotes":"298,666",
  "imdbID":"tt1535109",
  "Type":"movie",
  "Response":"True"
}
````

If you look at `Writer` you will see it contains a very ugly item (well, 2 really), ` Richard Phillips (based upon the book \"A Captain's Duty: Somali Pirates,  Navy SEALS,  and Dangerous Days at Sea\" by)` This will be split into 3 items due to the commas in the parenthesises. I am unsure whether this is an issue in omdb or the way the module consumes it?

As a solution I was thinking about rewriting the parsing of list items to a progressive way (as in reading until a token) and ignoring commas between parenthesises (`(`, `[`, `{`) until they are closed but if there is an unclosed tag that would result in an other issue so I am not sure if that would be an actual improvement. Any thoughts?

**Comment by misterhat** [comment]
Fixed in https://github.com/misterhat/omdb/commit/837374251f67e07b52aea0b009d652b775f47694. I removed all of the information in brackets as it's inconsistent at best and not worth keeping.
