### ISSUE TITLE
Possible to add "type" to omdb.get

### ISSUE THREAD

**Issue by dragonbanshee** [misterhat/omdb#17]
Is it possible to add the "type" parameter to the omdb.get method? It is available here: http://www.omdbapi.com/

I know it is in the search method, but it would be much better if it were available to the get method as well. Thanks.

**Comment by misterhat** [comment]
Thanks! Fixed in https://github.com/misterhat/omdb/commit/5f04c83107d37aa9538212d9386da2fe35de841d.
