### ISSUE TITLE
api key now required.

### ISSUE THREAD

**Issue by ghost** [misterhat/omdb#28]
The service is now private and requires an api key (minimum $1 donation per month on Patreon.)

https://www.patreon.com/posts/api-is-going-10743518

new url format is http://www.omdbapi.com/?i=tt3896198&apikey=[key]

also works http://www.omdbapi.com/?apikey=[key]&i=tt3896198

I have an api key to test, just can't figure out how to fix otherwise I'd submit a pull request lol.

edit:

So I have a temp fix, dirty code however. I only use queries per imdb id but it should work the same for querying by title.

https://github.com/misterhat/omdb/blob/master/index.js#L91
https://github.com/misterhat/omdb/blob/master/index.js#L153

change `var query = {};` to `var query = {apikey: 'key'};`

**Comment by ghost** [comment]
#29 Temp api fix for impatient people like me, until Mister Hat makes a proper fix.

**Comment by misterhat** [comment]
I'm not interested in maintaining this if an API key's needed. I can transfer ownership to whoever's interested.

**Comment by ghost** [comment]
I don't think it's a permanent solution. The issue came about with cloudflare and him getting billed an insane amount he cannot pay, but his end goal is to create a free api with rate limiting and max amount per day for free users, then paid options for increase requests, but has to implement this until he has some sort of user registration of sorts (afaik).

I don't know nodejs that well and wouldn't be comfortable taking over otherwise I would offer. My plan is 100k per day, the only thing I could suggest is seeing if shared use is okay, and if so I'd let you use my key so you could continue developing this.

**Comment by ghost** [comment]
@misterhat I guess if you want to transfer ownership, I will take it, I have some changes to push for fixing rotten tomatoes score, and some additions like seriesID, box office, website, dvd release date. Plus if anyone has future pull requests to help I can deal with that.
