### ISSUE TITLE
unexpected token o

### ISSUE THREAD

**Issue by lagzda** [misterhat/omdb#8]
Since the new update on the OmdbApi I have started to get the error "unexpected token o" when trying to use omdb.search.

**Comment by dragonbanshee** [comment]
This is fixed in [my pull request](https://github.com/misterhat/omdb/pull/9).

**Comment by lagzda** [comment]
Thank you

**Comment by misterhat** [comment]
Sorry about that, fixed in latest release. Thanks both of you.
